### ISSUE TITLE
Window is not defined with server side rendering

### ISSUE THREAD

**Issue by dbismut** [webpack-contrib/react-proxy-loader#17]
Hi! I'm fairly new to all this, so apologies if anything sounds dumb. I'm trying to create a text field which measures the strength of a password using [zxcvbn library from Dropbox](https://github.com/dropbox/zxcvbn). I want to load it async, so I placed `import zxcvbn from 'react-proxy!zxcvbn'` at the top of the component file.

Everything works fine in development, however, when I compile my project for production with SSR enabled, I get the following error: `ReferenceError: window is not defined`.

Is there a way to prevent the server from loading the library and keep that for the client? Also I tried the below instead of `react-proxy-loader` with no more luck:

``` javascript
componentDidMount() {
  if (!zxcvbn) {
    require(['zxcvbn'], function (obj) {
      zxcvbn = obj;
    });
  }
}
```

**Comment by dbismut** [comment]
I've solved my problem using https://github.com/dozoisch/react-async-script but I'd still be interested in the reason why I get this bug with `require`.

**Comment by jsg2021** [comment]
If you are doing server side rendering, you probably have two bundles, one for a browser client, one for node. In the node webpack config don't include this loader, leave it to be handled by the default loader.

**Comment by michael-ciniawsky** [comment]
@dbismut See @jsg2021 comment and feel free to reopen if still any regressions 😛
