### ISSUE TITLE
Source maps

### ISSUE THREAD

**Issue by simax** [webpack-contrib/react-proxy-loader#18]
Are people successfully using source maps with react-proxy-loader. A project I'm working on is using the code splitting facility of Webpack and react-proxy-loader. I'm having trouble actually getting source maps to work with it. I've used source maps successfully on other projects that don't use code splitting and wonder if this is the issue. The output from gulp task indicates that source maps are indeed being created - they just don't appear to be available in Chrome. Just wondered if there was anything special i need to do to make source-maps work with react-proxy-loader?

**Comment by nub4life** [comment]
I use react-proxy-loader and the sourcemaps generate with no problem. Are you doing the source maps in webpack: `devtool = #source-map` ?

**Comment by michael-ciniawsky** [comment]
@simax Is this still an issue ?

**Comment by simax** [comment]
I don't think I ever got a successful solution but I've moved on from project where I needed this behaviour. So if you're asking can this issue be closed then I guess it can as far as I'm concerned.
