### ISSUE TITLE
Does this library still maintained and will it continue to support React 0.14 and 15 ?

### ISSUE THREAD

**Issue by iroy2000** [webpack-contrib/react-proxy-loader#20]

**Comment by Pszek** [comment]
+1

**Comment by im4LF** [comment]
Anybody?

**Comment by rosskevin** [comment]
I found this, perhaps it is the best replacement?

https://github.com/buzzer13/react-ondemand-loader

**Comment by jsg2021** [comment]
It works just fine with React 0.14 and 15

**Comment by Sawtaytoes** [comment]
How do you use Mixins in the newer React versions?

**Comment by wzup** [comment]
@michael-ciniawsky why did you close the issue? Any for the last question?
